% load, clean and remove, get spike shapes. change V1 or LM according to ff
% or fb

% separate and pv and non-pv
wideind = find(cellfun(@(x) x.spikewidth>14, LMcells)); 
narrowind = find(cellfun(@(x) x.spikewidth<=12 , LMcells));
%%
cells = LMcells(wideind);
% median or mean?
bs = (cell2mat(cellfun(@(x) nanmean([nanmean(x.laAbs.go{1}),nanmean(x.laAbs.nogo{1}),...
    nanmean(x.laAbs.go{2}),nanmean(x.laAbs.nogo{2}),...
    nanmean(x.laAbs.go{3}),nanmean(x.laAbs.nogo{3}),...
    nanmean(x.laAbs.go{4}),nanmean(x.laAbs.nogo{4}),...
    nanmean(x.laAbs.go{5}),nanmean(x.laAbs.nogo{5}),...
    nanmean(x.laAbs.go{6}),nanmean(x.laAbs.nogo{6}),...
    nanmean(x.laAbs.go{7}),nanmean(x.laAbs.nogo{7}),...
    nanmean(x.laAbs.go{8}),nanmean(x.laAbs.nogo{8}),...
    ]),cells,'UniformOutput',0)))/0.15

ls = (cell2mat(cellfun(@(x) nanmean([nanmean(x.laAls.go{1}),nanmean(x.laAls.nogo{1}),...
    nanmean(x.laAls.go{2}),nanmean(x.laAls.nogo{2}),...
    nanmean(x.laAls.go{3}),nanmean(x.laAls.nogo{3}),...
    nanmean(x.laAls.go{4}),nanmean(x.laAls.nogo{4}),...
    nanmean(x.laAls.go{5}),nanmean(x.laAls.nogo{5}),...
    nanmean(x.laAls.go{6}),nanmean(x.laAls.nogo{6}),...
    nanmean(x.laAls.go{7}),nanmean(x.laAls.nogo{7}),...
    nanmean(x.laAls.go{8}),nanmean(x.laAls.nogo{8}),...
    ]),cells,'UniformOutput',0)))/0.15

nanmedian(bs)
nanmedian(ls)

100*nanmedian((ls - bs)./bs)
